import { LangContent, getTranslationWithContent } from "../../HOC/Translation.tsx/Translation";

export const content: LangContent = {
    'az': {
        'Profil məlumatları': 'Profil məlumatları',
        'Əlaqə məlumatları': 'Əlaqə məlumatları',
        'Tədris Mərkəzinə bağlı məlumatları': 'Tədris Mərkəzinə bağlı məlumatları',
        'Ad': 'Ad',
        'Soyad': 'Soyad',
        'Təhsil aldığı məktəb': 'Təhsil aldığı məktəb',
        'Doğum tarixi': 'Doğum tarixi',
        'Email': 'Email',
        'Əlaqə nömrəsi': 'Əlaqə nömrəsi',
        'Fin kodu': 'Fin kodu',
        'Filial': 'Filial',
        'Ünvan': 'Ünvan',
        'Şifrə': 'Şifrə',
        'Qrup': 'Qrup',
        'Müəllim': 'Müəllim',
        'Ölkə': 'Ölkə',
        'Şəhər': 'Şəhər'
    },
    'en': {
        'Profil məlumatları': 'Profile Information',
        'Əlaqə məlumatları': 'Contact Information',
        'Tədris Mərkəzinə bağlı məlumatları': 'Education Center Information',
        'Ad': 'First Name',
        'Soyad': 'Last Name',
        'Təhsil aldığı məktəb': 'School',
        'Doğum tarixi': 'Birth Date',
        'Email': 'Email',
        'Əlaqə nömrəsi': 'Phone Number',
        'Fin kodu': 'FIN Code',
        'Filial': 'Branch',
        'Ünvan': 'Address',
        'Şifrə': 'Password',
        'Qrup': 'Group',
        'Müəllim': 'Teacher',
        'Ölkə': 'Country',
        'Şəhər': 'City'
    },
    'ru': {
        'Profil məlumatları': 'Информация профиля',
        'Əlaqə məlumatları': 'Контактная информация',
        'Tədris Mərkəzinə bağlı məlumatları': 'Информация об учебном центре',
        'Ad': 'Имя',
        'Soyad': 'Фамилия',
        'Təhsil aldığı məктəб': 'Школа',
        'Doğum tarixi': 'Дата рождения',
        'Email': 'Email',
        'Əlaqə nömrəsi': 'Номер телефона',
        'Fin kodu': 'ФИН код',
        'Filial': 'Филиал',
        'Ünvan': 'Адрес',
        'Şifrə': 'Пароль',
        'Qrup': 'Группа',
        'Müəllim': 'Учитель',
        'Ölkə': 'Страна',
        'Şəhər': 'Город'
    },
    'tr': {
        'Profil məlumatları': 'Profil Bilgileri',
        'Əlaqə məlumatları': 'İletişim Bilgileri',
        'Tədris Mərkəzinə bağlı məlumatları': 'Eğitim Merkezi Bilgileri',
        'Ad': 'Ad',
        'Soyad': 'Soyad',
        'Təhsil aldığı məktəb': 'Okul',
        'Doğum tarixi': 'Doğum Tarihi',
        'Email': 'Email',
        'Əlaqə nömrəsi': 'Telefon Numarası',
        'Fin kodu': 'FIN Kodu',
        'Filial': 'Şube',
        'Ünvan': 'Adres',
        'Şifrə': 'Şifre',
        'Qrup': 'Grup',
        'Müəllim': 'Öğretmen',
        'Ölkə': 'Ülke',
        'Şəhər': 'Şehir'
    },
    'pl': {
        'Profil məlumatları': 'Informacje profilowe',
        'Əlaqə məlumatları': 'Informacje kontaktowe',
        'Tədris Mərkəzinə bağlı məlumatları': 'Informacje o centrum edukacyjnym',
        'Ad': 'Imię',
        'Soyad': 'Nazwisko',
        'Təhsil aldığı məktəb': 'Szkoła',
        'Doğum tarixi': 'Data urodzenia',
        'Email': 'Email',
        'Əlaqə nömrəsi': 'Numer telefonu',
        'Fin kodu': 'Kod FIN',
        'Filial': 'Oddział',
        'Ünvan': 'Adres',
        'Şifrə': 'Hasło',
        'Qrup': 'Grupa',
        'Müəllim': 'Nauczyciel',
        'Ölkə': 'Kraj',
        'Şəhər': 'Miasto'
    },
    'kk': {
        'Profil məlumatları': 'Профиль ақпараты',
        'Əlaqə məlumatları': 'Байланыс ақпараты',
        'Tədris Mərkəzinə bağlı məlumatları': 'Оқу орталығы ақпараты',
        'Ad': 'Аты',
        'Soyad': 'Тегі',
        'Təhsil aldığı məктəб': 'Мектеп',
        'Doğum tarixi': 'Туған күні',
        'Email': 'Email',
        'Əlaqə nömrəsi': 'Телефон нөірі',
        'Fin kodu': 'ЖСН коды',
        'Filial': 'Филиал',
        'Ünvan': 'Мекен-жай',
        'Şifrə': 'Құпия сөз',
        'Qrup': 'Топ',
        'Müəllim': 'Мұғалім',
        'Ölkə': 'Ел',
        'Şəhər': 'Қала'
    }
}

export default getTranslationWithContent(content);
