import { LangContent, getTranslationWithContent } from "../../HOC/Translation.tsx/Translation";
import { content as formulaLangContent } from "../../pages/formules/Lang";

export const content: LangContent = {
    'az': {
        'Formul': 'Formul',
        'Rəqəm sayı': 'Rəqəm sayı',
        'Ədəd sayı': 'Ədəd sayı',
        'Ədədlərarası saniyə': 'Ədədlərarası saniyə',
        'YENİLƏ': 'YENİLƏ',
        'Hazır ol': 'Hazır ol',
        'Başla': 'Başla',
        'Qalan Oyun sayı': 'Qalan Oyun sayı',
        'Sizin Cavab': 'Sizin Cavab',
        'Doğru Cavab': 'Doğru Cavab',
        'Ümumi Doğru': 'Ümumi Doğru',
        'Ümumi Yanlış': 'Ümumi Yanlış',
        'AFƏRİN': 'AFƏRİN',
        'DOĞRU': 'DOĞRU',
        'YANLIŞ': 'YANLIŞ',
        'OYUN SAYI': 'OYUN SAYI',
        'Sən dahisən!': 'Sən dahisən!',
        'Cavabla': 'Cavabla',
        'Növbəti': 'Növbəti',
        'Yenidən oyna': 'Yenidən oyna',
        ...formulaLangContent['az'],
        
    },
    'en': {
        'Formul': 'Formula',
        'Rəqəm sayı': 'Number of Digits',
        'Ədəd sayı': 'Number of Numbers',
        'Ədədlərarası saniyə': 'Seconds Between Numbers',
        'YENİLƏ': 'Refresh',
        'Hazır ol': 'Get Ready',
        'Başla': 'Start',
        'Qalan Oyun sayı': 'Remaining Games',
        'Sizin Cavab': 'Your Answer',
        'Doğru Cavab': 'Correct Answer',
        'Ümumi Doğru': 'Total Correct',
        'Ümumi Yanlış': 'Total Incorrect',
        'AFƏRİN': 'WELL DONE',
        'DOĞRU': 'CORRECT',
        'YANLIŞ': 'INCORRECT',
        'OYUN SAYI': 'GAME COUNT',
        'Sən dahisən!': 'You are a genius!',
        'Cavabla': 'Answer',
        'Növbəti': 'Next',
        'Yenidən oyna': 'Play Again',
        ...formulaLangContent['en'],
    },
    'ru': {
        'Formul': 'Формула',
        'Rəqəm sayı': 'Количество цифр',
        'Ədəd sayı': 'Количество чисел',
        'Ədədlərarası saniyə': 'Секунды между числами',
        'YENİLƏ': 'Обновить',
        'Hazır ol': 'Приготовьтесь',
        'Başla': 'Начать',
        'Qalan Oyun sayı': 'Оставшиеся игры',
        'Sizin Cavab': 'Ваш ответ',
        'Doğru Cavab': 'Правильный ответ',
        'Ümumi Doğru': 'Всего правильно',
        'Ümumi Yanlış': 'Всего неправильно',
        'AFƏRİN': 'МОЛОДЕЦ',
        'DOĞRU': 'ПРАВИЛЬНО',
        'YANLIŞ': 'НЕПРАВИЛЬНО',
        'OYUN SAYI': 'КОЛИЧЕСТВО ИГР',
        'Sən dahisən!': 'Вы гений!',
        'Cavabla': 'Ответить',
        'Növbəti': 'Следующий',
        'Yenidən oyna': 'Играть снова',
        ...formulaLangContent['ru'],
    },
    'tr': {
        'Formul': 'Formül',
        'Rəqəm sayı': 'Rakam Sayısı',
        'Ədəd sayı': 'Sayı Adedi',
        'Ədədlərarası saniyə': 'Sayılar Arası Saniye',
        'YENİLƏ': 'Yenile',
        'Hazır ol': 'Hazır Ol',
        'Başla': 'Başla',
        'Qalan Oyun sayı': 'Kalan Oyun Sayısı',
        'Sizin Cavab': 'Cevabınız',
        'Doğru Cavab': 'Doğru Cevap',
        'Ümumi Doğru': 'Toplam Doğru',
        'Ümumi Yanlış': 'Toplam Yanlış',
        'AFƏRİN': 'Aferin',
        'DOĞRU': 'DOĞRU',
        'YANLIŞ': 'YANLIŞ',
        'OYUN SAYI': 'OYUN SAYISI',
        'Sən dahisən!': 'Sen bir dahisin!',
        'Cavabla': 'Cevapla',
        'Növbəti': 'Sonraki',
        'Yenidən oyna': 'Tekrar Oyna',
        ...formulaLangContent['tr'],
    },
    'pl': {
        'Formul': 'Formuła',
        'Rəqəm sayı': 'Liczba Cyfr',
        'Ədəd sayı': 'Liczba Liczb',
        'Ədədlərarası saniyə': 'Sekundy Między Liczbami',
        'YENİLƏ': 'Odśwież',
        'Hazır ol': 'Przygotuj się',
        'Başla': 'Start',
        'Qalan Oyun sayı': 'Pozostałe Gry',
        'Sizin Cavab': 'Twoja Odpowiedź',
        'Doğru Cavab': 'Poprawna Odpowiedź',
        'Ümumi Doğru': 'Łącznie Poprawnych',
        'Ümumi Yanlış': 'Łącznie Błędnych',
        'AFƏRİN': 'BRAWO',
        'DOĞRU': 'POPRAWNE',
        'YANLIŞ': 'BŁĘDNE',
        'OYUN SAYI': 'LICZBA GIER',
        'Sən dahisən!': 'Jesteś geniuszem!',
        'Cavabla': 'Odpowiedz',
        'Növbəti': 'Następny',
        'Yenidən oyna': 'Zagraj Ponownie',
        ...formulaLangContent['pl'],
    },
    'kz': {
        'Formul': 'Формула',
        'Rəqəm sayı': 'Сандар саны',
        'Ədəd sayı': 'Сандар саны',
        'Ədədlərarası saniyə': 'Сандар арасындағы секундтар',
        'YENİLƏ': 'Жаңарту',
        'Hazır ol': 'Дайын бол',
        'Başla': 'Бастау',
        'Qalan Oyun sayı': 'Қалған ойындар саны',
        'Sizin Cavab': 'Сіздің жауабыңыз',
        'Doğru Cavab': 'Дұрыс жауап',
        'Ümumi Doğru': 'Жалпы дұрыс',
        'Ümumi Yanlış': 'Жалпы қате',
        'AFƏRİN': 'ЖАРАЙСЫҢ',
        'DOĞRU': 'ДҰРЫС',
        'YANLIŞ': 'ҚАТЕ',
        'OYUN SAYI': 'ОЙЫН САНЫ',
        'Sən dahisən!': 'Сен данышпансың!',
        'Cavabla': 'Жауап беру',
        'Növbəti': 'Келесі',
        'Yenidən oyna': 'Қайта ойнау',
        ...formulaLangContent['kz'],
    },
}




export default getTranslationWithContent(content);
