import { LangContent, getTranslationWithContent } from "../../HOC/Translation.tsx/Translation";
import { content as formulaLangContent } from "../../pages/formules/Lang";
import { content as actionLangContent } from "../../pages/actions/Lang";

export const content: LangContent = {
    'az': {
        'Formul': 'Formul',
        'Rəqəm sayı': 'Rəqəm sayı',
        'Oyun sayı': 'Oyun sayı',
        'İkinci rəqəm sayı': 'İkinci rəqəm sayı',
        'Ədəd sayı': 'Ədəd sayı',
        'Ədədlərarası saniyə': 'Ədədlərarası saniyə',
        'Cavab üçün saniyə': 'Cavab üçün saniyə',
        'YENİLƏ': 'YENİLƏ',
        'Hazır ol': 'Hazır ol',
        'Başla': 'Başla',
        'Qalan Oyun Sayı': 'Qalan Oyun Sayı',
        'Sizin Cavab': 'Sizin Cavab',
        'Doğru Cavab': 'Doğru Cavab',
        'Ümumi Doğru': 'Ümumi Doğru',
        'Ümumi Yanlış': 'Ümumi Yanlış',
        'AFƏRİN': 'AFƏRİN',
        'DOĞRU': 'DOĞRU',
        'YANLIŞ': 'YANLIŞ',
        'OYUN SAYI': 'OYUN SAYI',
        'Sən dahisən!': 'Sən dahisən!',
        'Cavabla': 'Cavabla',
        'Növbəti': 'Növbəti',
        'Yenidən oyna': 'Yenidən oyna',
        'Nəticə': 'Nəticə',
        'Mod': 'Mod',
        'Birinci rəqəm sayı ikincidən kiçik ola bilməz': 'Birinci rəqəm sayı ikincidən kiçik ola bilməz',
        ...formulaLangContent['az'],
        ...actionLangContent['az'],

    },
    'en': {
        'Formul': 'Formula',
        'Rəqəm sayı': 'Number of Digits',
        'Oyun sayı': 'Number of Games',
        'İkinci rəqəm sayı': 'Number of Second Digits',
        'Ədəd sayı': 'Number of Numbers',
        'Ədədlərarası saniyə': 'Seconds Between Numbers',
        'Cavab üçün saniyə': 'Seconds for Answer',
        'YENİLƏ': 'Refresh',
        'Hazır ol': 'Get Ready',
        'Başla': 'Start',
        'Qalan Oyun Sayı': 'Remaining Games',
        'Sizin Cavab': 'Your Answer',
        'Doğru Cavab': 'Correct Answer',
        'Ümumi Doğru': 'Total Correct',
        'Ümumi Yanlış': 'Total Incorrect',
        'AFƏRİN': 'WELL DONE',
        'DOĞRU': 'CORRECT',
        'YANLIŞ': 'INCORRECT',
        'OYUN SAYI': 'GAME COUNT',
        'Sən dahisən!': 'You are a genius!',
        'Cavabla': 'Answer',
        'Növbəti': 'Next',
        'Yenidən oyna': 'Play Again',
        'Nəticə': 'Result',
        'Mod': 'Mode',
        'Birinci rəqəm sayı ikincidən kiçik ola bilməz': 'First digit count cannot be less than second digit count',
        ...formulaLangContent['en'],
        ...actionLangContent['en'],
    },
    'ru': {
        'Formul': 'Формула',
        'Rəqəm sayı': 'Количество цифр',
        'Oyun sayı': 'Количество игр',
        'İkinci rəqəm sayı': 'Количество второй цифры',
        'Ədəd sayı': 'Количество чисел',
        'Ədədlərarası saniyə': 'Секунды между числами',
        'Cavab üçün saniyə': 'Секунды для ответа',
        'YENİLƏ': 'Обновить',
        'Hazır ol': 'Приготовьтесь',
        'Başla': 'Начать',
        'Qalan Oyun Sayı': 'Оставшиеся игры',
        'Sizin Cavab': 'Ваш ответ',
        'Doğru Cavab': 'Правильный ответ',
        'Ümumi Doğru': 'Всего правильно',
        'Ümumi Yanlış': 'Всего неправильно',
        'AFƏRİN': 'МОЛОДЕЦ',
        'DOĞRU': 'ПРАВИЛЬНО',
        'YANLIŞ': 'НЕПРАВИЛЬНО',
        'OYUN SAYI': 'КОЛИЧЕСТВО ИГР',
        'Sən dahisən!': 'Вы гений!',
        'Cavabla': 'Ответить',
        'Növbəti': 'Следующий',
        'Yenidən oyna': 'Играть снова',
        'Nəticə': 'Результат',
        'Mod': 'Режим',
        'Birinci rəqəm sayı ikincidən kiçik ola bilməz': 'Количество первых цифр не может быть меньше вторых',
        ...formulaLangContent['ru'],
        ...actionLangContent['ru'],
    },
    'tr': {
        'Formul': 'Formül',
        'Rəqəm sayı': 'Rakam Sayısı',
        'Oyun sayı': 'Oyun Sayısı',
        'İkinci rəqəm sayı': 'İkinci Rakam Sayısı',
        'Ədəd sayı': 'Sayı Adedi',
        'Ədədlərarası saniyə': 'Sayılar Arası Saniye',
        'Cavab üçün saniyə': 'Cavab Saniyesi',
        'YENİLƏ': 'Yenile',
        'Hazır ol': 'Hazır Ol',
        'Başla': 'Başla',
        'Qalan Oyun Sayı': 'Kalan Oyun Sayısı',
        'Sizin Cavab': 'Cevabınız',
        'Doğru Cavab': 'Doğru Cevap',
        'Ümumi Doğru': 'Toplam Doğru',
        'Ümumi Yanlış': 'Toplam Yanlış',
        'AFƏRİN': 'Aferin',
        'DOĞRU': 'DOĞRU',
        'YANLIŞ': 'YANLIŞ',
        'OYUN SAYI': 'OYUN SAYISI',
        'Sən dahisən!': 'Sen bir dahisin!',
        'Cavabla': 'Cevapla',
        'Növbəti': 'Sonraki',
        'Yenidən oyna': 'Tekrar Oyna',
        'Nəticə': 'Sonuç',
        'Mod': 'Mod',
        'Birinci rəqəm sayı ikincidən kiçik ola bilməz': 'Birinci rakam sayısı ikinciden küçük olamaz',
        ...formulaLangContent['tr'],
        ...actionLangContent['tr'],
    },
    'pl': {
        'Formul': 'Formuła',
        'Rəqəm sayı': 'Liczba Cyfr',
        'Oyun sayı': 'Liczba Gier',
        'İkinci rəqəm sayı': 'Liczba Drugiej Cyfry',
        'Ədəd sayı': 'Liczba Liczb',
        'Ədədlərarası saniyə': 'Sekundy Między Liczbami',
        'Cavab üçün saniyə': 'Sekundy na Odpowiedź',
        'YENİLƏ': 'Odśwież',
        'Hazır ol': 'Przygotuj się',
        'Başla': 'Start',
        'Qalan Oyun Sayı': 'Pozostałe Gry',
        'Sizin Cavab': 'Twoja Odpowiedź',
        'Doğru Cavab': 'Poprawna',
        'Ümumi Doğru': 'Łącznie Poprawnych',
        'Ümumi Yanlış': 'Łącznie Błędnych',
        'AFƏRİN': 'BRAWO',
        'DOĞRU': 'POPRAWNE',
        'YANLIŞ': 'BŁĘDNE',
        'OYUN SAYI': 'LICZBA GIER',
        'Sən dahisən!': 'Jesteś geniuszem!',
        'Cavabla': 'Odpowiedz',
        'Növbəti': 'Następny',
        'Yenidən oyna': 'Zagraj Ponownie',
        'Nəticə': 'Wynik',
        'Mod': 'Tryb',
        'Birinci rəqəm sayı ikincidən kiçik ola bilməz': 'Liczba pierwszych cyfr nie może być mniejsza niż drugich',
        ...formulaLangContent['pl'],
        ...actionLangContent['pl'],
    },
    'kk': {
        'Formul': 'Формула',
        'Rəqəm sayı': 'Сандар саны',
        'Oyun sayı': 'Ойын саны',
        'İkinci rəqəm sayı': 'Сандар саны',
        'Ədəd sayı': 'Сандар саны',
        'Ədədlərarası saniyə': 'Сандар арасындағы секундтар',
        'Cavab üçün saniyə': 'Секундалар жауап үшін',
        'YENİLƏ': 'Жаңарту',
        'Hazır ol': 'Дайын бол',
        'Başla': 'Бастау',
        'Qalan Oyun Sayı': 'Қалған ойындар саны',
        'Sizin Cavab': 'Сіздің жауабыңыз',
        'Doğru Cavab': 'Дұрыс жауап',
        'Ümumi Doğru': 'Жалпы дұрыс',
        'Ümumi Yanlış': 'Жалпы қате',
        'AFƏRİN': 'ЖАРАЙСЫҢ',
        'DOĞRU': 'ДҰРЫС',
        'YANLIŞ': 'ҚАТЕ',
        'OYUN SAYI': 'ОЙЫН САНЫ',
        'Sən dahisən!': 'Сен данышпансың!',
        'Cavabla': 'Жауап беру',
        'Növbəti': 'Келесі',
        'Yenidən oyna': 'Қайта ойнау',
        'Nəticə': 'Нәтиже',
        'Mod': 'Режим',
        'Birinci rəqəm sayı ikincidən kiçik ola bilməz': 'Бірінші сандар саны екіншіден кем болмауы керек',
        ...formulaLangContent['kk'],
        ...actionLangContent['kk'],
    },
}




export default getTranslationWithContent(content);
