import { LangContent, getTranslationWithContent } from "../../HOC/Translation.tsx/Translation";


export const content: LangContent = {
    'az': {
        'Rəqəm sayı': 'Rəqəm sayı',
        'Ədəd sayı': 'Ədəd sayı',
        'Cavab müddəti': 'Cavab müddəti',
        'Giriş animasiyası saniyə': 'Giriş animasiyası saniyə',
        'Çıxış animasiyası saniyə': 'Çıxış animasiyası saniyə',
        'Növbəti': 'Növbəti',
        'Geri': 'Geri',
        'Başla': 'Başla',
        'Formullar': 'Formullar',
        'Formul izahı üçün': 'Formul izahı üçün',
        'Əl ilə izah': 'Əl ilə izah',
        'Abak ilə izah': 'Abak ilə izah',
        'Rəqəm sayı seç': 'Rəqəm sayı seç',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Oynamaq istədiyiniz ədəd sayını seçin',
        'Oyun sayı': 'Oyun sayı',
        'Oyun sayını qeyd edin': 'Oyun sayını qeyd edin',
        'Rəqəm sayı qarışıq olsun': 'Rəqəm sayı qarışıq olsun',
        'Link kopyalandı': 'Link kopyalandı',
        'Ədəd və cavab gəlmə müddətini seçin.': 'Ədəd və cavab gəlmə müddətini seçin.',
        'Ədədlərarası saniyə': 'Ədədlərarası saniyə',
        'Animasiya olsun': 'Animasiya olsun',
        'Cavab üçün saniyə': 'Cavab üçün saniyə',
        'Oyunu başlat': 'Oyunu başlat',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Oyunu başlatmaq üçün linki kopyalayın',
        'Link kopyala': 'Link kopyala',
        'Tar': 'Tar',
        'Kaman': 'Kaman',
        'Nagara': 'Nagara',
        'Forte Piano': 'Forte Piano',
        'Qarmon': 'Qarmon',
        'Saz': 'Saz',
        'Tütək': 'Tütək',
        'Qanun': 'Qanun',
        'Qara Zurna': 'Qara Zurna',
        'Ud': 'Ud',
        'İt': 'İt',
        'Xoruz': 'Xoruz',
        'Quzu': 'Quzu',
        'Canavar': 'Canavar',
        'Bülbül': 'Bülbül',
        'İnək': 'İnək',
        'Arı': 'Arı',
        'Pişik': 'Pişik',
        'Qurbağa': 'Qurbağa',
        'At': 'At',
        'Vurma cədvəli': 'Vurma Cədvəli',
        'Qüvvət cədvəli': 'Qüvvət Cədvəli',
        'Alət səsləri': 'Alət Səsləri',
        'Heyvan səsləri': 'Heyvan Səsləri',
        'Vurma və bölmə cədvəlini öyrənək': 'Vurma və bölmə cədvəlini öyrənək',
        'Qüvvət cədvəlini öyrənək': 'Qüvvət cədvəlini öyrənək',
        'Rəqəmlərə uyğun səsləri öyrən': 'Rəqəmlərə uyğun səsləri öyrən',
        'Ədəd': 'Ədəd',
    },
    'en': {
        'Rəqəm sayı': 'Number of digits',
        'Ədəd sayı': 'Number of numbers',
        'Cavab müddəti': 'Answer duration',
        'Giriş animasiyası saniyə': 'Enter animation duration',
        'Çıxış animasiyası saniyə': 'Exit animation duration',
        'NÖVBƏTİ': 'FORWARD',
        'GERİ': 'BACK',
        'BAŞLA': 'START',
        'Formullar': 'Formulas',
        'Formul izahı üçün': 'For formula explanation',
        'ƏL İLƏ İZAH': 'Explanation by hand',
        'ABAK İLƏ İZAH': 'Explanation with abacus',
        'Rəqəm sayı seç': 'Choose number of digits',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'How many numbers do you want to play with?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Select the number of numbers you want to play with',
        'Oyun sayı': 'Number of games',
        'Oyun sayını qeyd edin': 'Enter the number of games',
        'Rəqəm sayı qarışıq olsun': 'Mix the number of digits',
        'Link kopyalandı': 'Link copied',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Select the number and answer arrival time.',
        'Ədədlərarası saniyə': 'Seconds between numbers',
        'Cavab üçün saniyə': 'Seconds for answer',
        'Animasiya olsun': 'Enable animation',
        'Oyunu başlat': 'Start the game',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Copy the link to start the game',
        'Link Kopyala': 'Copy Link',
        'Tar': 'Tar',
        'Kaman': 'Kaman',
        'Nagara': 'Nagara',
        'Forte Piano': 'Forte Piano',
        'Qarmon': 'Accordion',
        'Saz': 'Saz',
        'Tutek': 'Flute',
        'Qanun': 'Kanun',
        'Qara Zurna': 'Black Zurna',
        'Ud': 'Oud',
        'İt': 'Dog',
        'Xoruz': 'Rooster',
        'Quzu': 'Lamb',
        'Canavar': 'Wolf',
        'Bülbül': 'Nightingale',
        'İnək': 'Cow',
        'Arı': 'Bee',
        'Pişik': 'Cat',
        'Qurbağa': 'Frog',
        'At': 'Horse',
        'Vurma Cədvəli': 'Multiplication Table',
        'Qüvvət Cədvəli': 'Power Table',
        'Alət Səsləri': 'Instrument Sounds',
        'Heyvan Səsləri': 'Animal Sounds',
        'Vurma və bölmə cədvəlini öyrənək': 'Let\'s learn the multiplication and division table',
        'Qüvvət cədvəlini öyrənək': 'Let\'s learn the power table',
        'Rəqəmlərə uyğun səsləri öyrən': 'Learn the sounds corresponding to the numbers',
        'Ədəd': 'Number',
    },
    'ru': {
        'Rəqəm sayı': 'Количество цифр',
        'Ədəd sayı': 'Количество чисел',
        'Cavab müddəti': 'Время ответа',
        'Giriş animasiyası saniyə': 'Время ввода',
        'Çıxış animasiyası saniyə': 'Время вывода',
        'NÖVBƏTİ': 'ВПЕРЕД',
        'GERİ': 'НАЗАД',
        'BAŞLA': 'СТАРТ',
        'Formullar': 'Формулы',
        'Formul izahı üçün': 'Для объяснения формулы',
        'ƏL İLƏ İZAH': 'Объяснение вручную',
        'ABAK İLƏ İZAH': 'Объяснение с помощью абака',
        'Rəqəm sayı seç': 'Выберите количество цифр',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Сколько чисел вы хотите использовать в игре?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Выберите количество чисел, с которыми хотите играть',
        'Oyun sayı': 'Количество игр',
        'Oyun sayını qeyd edin': 'Введите количество игр',
        'Rəqəm sayı qarışıq olsun': 'Перемешать количество цифр',
        'Link kopyalandı': 'Ссылка скопирована',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Выберите время появления числа и ответа.',
        'Ədədlərarası saniyə': 'Секунды между числами',
        'Cavab üçün saniyə': 'Секунды для ответа',
        'Animasiya olsun': 'Включить анимацию',
        'Oyunu başlat': 'Начать игру',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Скопируйте ссылку, чтобы начать игру',
        'Link Kopyala': 'Скопировать ссылку',
        'Tar': 'Тар',
        'Kaman': 'Каман',
        'Nagara': 'Нагара',
        'Forte Piano': 'Фортепиано',
        'Qarmon': 'Гармонь',
        'Saz': 'Саз',
        'Tutek': 'Флейта',
        'Qanun': 'Канун',
        'Qara Zurna': 'Чёрная зурна',
        'Ud': 'Уд',
        'İt': 'Собака',
        'Xoruz': 'Петух',
        'Quzu': 'Ягнёнок',
        'Canavar': 'Волк',
        'Bülbül': 'Соловей',
        'İnək': 'Корова',
        'Arı': 'Пчела',
        'Pişik': 'Кошка',
        'Qurbağa': 'Лягушка',
        'At': 'Лошадь',
        'Vurma Cədvəli': 'Таблица умножения',
        'Qüvvət Cədvəli': 'Таблица степеней',
        'Alət Səsləri': 'Звуки инструментов',
        'Heyvan Səsləri': 'Звуки животных',
        'Vurma və bölmə cədvəlini öyrənək': 'Давайте изучим таблицу умножения и деления',
        'Qüvvət cədvəlini öyrənək': 'Давайте изучим таблицу степеней',
        'Rəqəmlərə uyğun səsləri öyrən': 'Изучите звуки, соответствующие цифрам',
        'Ədəd': 'Число',
    },
    'tr': {
        'Rəqəm sayı': 'Rakam sayısı',
        'Ədəd sayı': 'Sayı adedi',
        'Cavab müddəti': 'Cevap süresi',
        'Giriş animasiyası saniyə': 'Giriş animasyon süresi',
        'Çıxış animasiyası saniyə': 'Çıxış animasyon süresi',
        'NÖVBƏTİ': 'İLERİ',
        'GERİ': 'GERİ',
        'BAŞLA': 'BAŞLA',
        'Formullar': 'Formüller',
        'Formul izahı üçün': 'Formül açıklaması için',
        'ƏL İLƏ İZAH': 'Elle açıklama',
        'ABAK İLƏ İZAH': 'Abaküs ile açıklama',
        'Rəqəm sayı seç': 'Rakam sayısını seç',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Kaç adet sayı ile oynamak istersiniz?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Oynamak istediğiniz sayı adedini seçin',
        'Oyun sayı': 'Oyun sayısı',
        'Oyun sayını qeyd edin': 'Oyun sayısını girin',
        'Rəqəm sayı qarışıq olsun': 'Rakam sayısı karışık olsun',
        'Link kopyalandı': 'Bağlantı kopyalandı',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Sayı ve cevap gelme süresini seçin.',
        'Ədədlərarası saniyə': 'Sayılar arası saniye',
        'Cavab üçün saniyə': 'Cevap için saniye',
        'Animasiya olsun': 'Animasyonu etkinleştir',
        'Oyunu başlat': 'Oyunu başlat',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Oyunu başlatmak için bağlantıyı kopyalayın',
        'Link Kopyala': 'Bağlantıyı Kopyala',
        'Tar': 'Tar',
        'Kaman': 'Keman',
        'Nagara': 'Nagara',
        'Forte Piano': 'Piyano',
        'Qarmon': 'Akkordeon',
        'Saz': 'Saz',
        'Tutek': 'Flüt',
        'Qanun': 'Kanun',
        'Qara Zurna': 'Kara Zurna',
        'Ud': 'Ud',
        'İt': 'Köpek',
        'Xoruz': 'Horoz',
        'Quzu': 'Kuzu',
        'Canavar': 'Kurt',
        'Bülbül': 'Bülbül',
        'İnək': 'İnek',
        'Arı': 'Arı',
        'Pişik': 'Kedi',
        'Qurbağa': 'Kurbağa',
        'At': 'At',
        'Vurma Cədvəli': 'Çarpım Tablosu',
        'Qüvvət Cədvəli': 'Kuvvet Tablosu',
        'Alət Səsləri': 'Enstrüman Sesleri',
        'Heyvan Səsləri': 'Hayvan Sesleri',
        'Vurma və bölmə cədvəlini öyrənək': 'Çarpma ve bölme tablosunu öğrenelim',
        'Qüvvət cədvəlini öyrənək': 'Kuvvet tablosunu öğrenelim',
        'Rəqəmlərə uyğun səsləri öyrən': 'Rakamlarla uyumlu sesleri öğren',
        'Ədəd': 'Sayı',
    },
    'pl': {
        'Rəqəm sayı': 'Liczba cyfr',
        'Ədəd sayı': 'Liczba liczb',
        'Cavab müddəti': 'Czas odpowiedzi',
        'Giriş animasiyası saniyə': 'Czas wprowadzenia',
        'Çıxış animasiyası saniyə': 'Czas wyjścia',
        'NÖVBƏTİ': 'NAPRZÓD',
        'GERİ': 'WSTECZ',
        'BAŞLA': 'START',
        'Formullar': 'Formuły',
        'Formul izahı üçün': 'Do wyjaśnienia formuły',
        'ƏL İLƏ İZAH': 'Wyjaśnienie ręczne',
        'ABAK İLƏ İZAH': 'Wyjaśnienie za pomocą liczydła',
        'Rəqəm sayı seç': 'Wybierz liczbę cyfr',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Ile liczb chcesz użyć w grze?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Wybierz liczbę liczb, z którymi chcesz grać',
        'Oyun sayı': 'Liczba gier',
        'Oyun sayını qeyd edin': 'Wpisz liczbę gier',
        'Rəqəm sayı qarışıq olsun': 'Wymieszaj liczbę cyfr',
        'Link kopyalandı': 'Link skopiowany',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Wybierz czas pojawienia się liczby i odpowiedzi.',
        'Ədədlərarası saniyə': 'Sekundy między liczbami',
        'Cavab üçün saniyə': 'Sekundy na odpowiedź',
        'Animasiya olsun': 'Włącz animację',
        'Oyunu başlat': 'Rozpocznij grę',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Skopiuj link, aby rozpocząć grę',
        'Link Kopyala': 'Kopiuj link',
        'Tar': 'Tar',
        'Kaman': 'Kaman',
        'Nagara': 'Nagara',
        'Forte Piano': 'Fortepian',
        'Qarmon': 'Akordeon',
        'Saz': 'Saz',
        'Tutek': 'Flet',
        'Qanun': 'Kanun',
        'Qara Zurna': 'Czarna Zurna',
        'Ud': 'Ud',
        'İt': 'Pies',
        'Xoruz': 'Kogut',
        'Quzu': 'Jagnię',
        'Canavar': 'Wilk',
        'Bülbül': 'Słowik',
        'İnək': 'Krowa',
        'Arı': 'Pszczoła',
        'Pişik': 'Kot',
        'Qurbağa': 'Żaba',
        'At': 'Koń',
        'Vurma Cədvəli': 'Tablica mnożenia',
        'Qüvvət Cədvəli': 'Tablica potęg',
        'Alət Səsləri': 'Dźwięki instrumentów',
        'Heyvan Səsləri': 'Dźwięki zwierząt',
        'Vurma və bölmə cədvəlini öyrənək': 'Nauczmy się tabliczki mnożenia i dzielenia',
        'Qüvvət cədvəlini öyrənək': 'Nauczmy się tabliczki potęg',
        'Rəqəmlərə uyğun səsləri öyrən': 'Naucz się dźwięków odpowiadających liczbom',
        'Ədəd': 'Liczba',
    },
    'kz': {
        'Rəqəm sayı': 'Сандар саны',
        'Ədəd sayı': 'Сандар саны',
        'Cavab müddəti': 'Жауап уақыты',
        'Giriş animasiyası saniyə': 'Кіру анимациясының уақыты',
        'Çıxış animasiyası saniyə': 'Шығу анимациясының уақыты',
        'NÖVBƏTİ': 'АЛҒА',
        'GERİ': 'АРТҚА',
        'BAŞLA': 'БАСТАУ',
        'Formullar': 'Формулалар',
        'Formul izahı üçün': 'Формуланы түсіндіру үшін',
        'ƏL İLƏ İZAH': 'Қолмен түсіндіру',
        'ABAK İLƏ İZAH': 'Абакпен түсіндіру',
        'Rəqəm sayı seç': 'Сандар санын таңдаңыз',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Ойынға қанша санмен ойнағыңыз келеді?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Ойнағыңыз келетін сандар санын таңдаңыз',
        'Oyun sayı': 'Ойын саны',
        'Oyun sayını qeyd edin': 'Ойын санын енгізіңіз',
        'Rəqəm sayı qarışıq olsun': 'Сандар саны аралас болсын',
        'Link kopyalandı': 'Сілтеме көшірілді',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Сандар мен жауап келу уақытын таңдаңыз.',
        'Ədədlərarası saniyə': 'Сандар арасындағы секундтар',
        'Cavab üçün saniyə': 'Жауап үшін секундтар',
        'Animasiya olsun': 'Анимацияны қосыңыз',
        'Oyunu başlat': 'Ойынды бастау',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Ойынды бастау үшін сілтемені көшіріңіз',
        'Link Kopyala': 'Сілтемені көшіру',
        'Tar': 'Тар',
        'Kaman': 'Каман',
        'Nagara': 'Нагара',
        'Forte Piano': 'Фортепиано',
        'Qarmon': 'Гармонь',
        'Saz': 'Саз',
        'Tutek': 'Флейта',
        'Qanun': 'Канун',
        'Qara Zurna': 'Қара Зурна',
        'Ud': 'Уд',
        'İt': 'Ит',
        'Xoruz': 'Қораз',
        'Quzu': 'Қозы',
        'Canavar': 'Қасқыр',
        'Bülbül': 'Бұлбұл',
        'İnək': 'Сиыр',
        'Arı': 'Ара',
        'Pişik': 'Мысық',
        'Qurbağa': 'Бақа',
        'At': 'Жылқы',
        'Vurma Cədvəli': 'Көбейту кестесі',
        'Qüvvət Cədvəli': 'Дәреже кестесі',
        'Alət Səsləri': 'Аспап дыбыстары',
        'Heyvan Səsləri': 'Жануарлар дыбыстары',
        'Vurma və bölmə cədvəlini öyrənək': 'Көбейту және бөлу кестесін үйренейік',
        'Qüvvət cədvəlini öyrənək': 'Дәреже кестесін үйренейік',
        'Rəqəmlərə uyğun səsləri öyrən': 'Сандарға сәйкес дыбыстарды үйрен',
        'Ədəd': 'Сан',
    },
}


export default getTranslationWithContent(content);

