import { LangContent, getTranslationWithContent } from "../../HOC/Translation.tsx/Translation";


export const content: LangContent = {
    'az': {
        'Rəqəm sayı': 'Rəqəm sayı',
        'Ədəd sayı': 'Ədəd sayı',
        'Cavab müddəti': 'Cavab müddəti',
        'İRƏLİ': 'İRƏLİ',
        'GERİ': 'GERİ',
        'BAŞLA': 'BAŞLA',
        'Formullar': 'Formullar',
        'Formul izahı üçün': 'Formul izahı üçün',
        'ƏL İLƏ İZAH': 'ƏL İLƏ İZAH',
        'ABAK İLƏ İZAH': 'ABAK İLƏ İZAH',
        'Rəqəm sayı seç': 'Rəqəm sayı seç',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Oynamaq istədiyiniz ədəd sayını seçin',
        'Oyun sayı': 'Oyun sayı',
        'Oyun sayını qeyd edin': 'Oyun sayını qeyd edin',
        'Rəqəm sayı qarışıq olsun': 'Rəqəm sayı qarışıq olsun',
        'Link kopyalandı': 'Link kopyalandı',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'ƏDƏD və CAVAB gəlmə müddətini seçin.',
        'Ədədlərarası saniyə': 'Ədədlərarası saniyə',
        'Cavab üçün saniyə': 'Cavab üçün saniyə',
        'Oyunu başlat': 'Oyunu başlat',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Oyunu başlatmaq üçün linki kopyalayın',
        'Link Kopyala': 'Link Kopyala',
    },
    'en': {
        'Rəqəm sayı': 'Number of digits',
        'Ədəd sayı': 'Number of numbers',
        'Cavab müddəti': 'Answer duration',
        'İRƏLİ': 'FORWARD',
        'GERİ': 'BACK',
        'BAŞLA': 'START',
        'Formullar': 'Formulas',
        'Formul izahı üçün': 'For formula explanation',
        'ƏL İLƏ İZAH': 'Explanation by hand',
        'ABAK İLƏ İZAH': 'Explanation with abacus',
        'Rəqəm sayı seç': 'Choose number of digits',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'How many numbers do you want to play with?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Select the number of numbers you want to play with',
        'Oyun sayı': 'Number of games',
        'Oyun sayını qeyd edin': 'Enter the number of games',
        'Rəqəm sayı qarışıq olsun': 'Mix the number of digits',
        'Link kopyalandı': 'Link copied',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Select the number and answer arrival time.',
        'Ədədlərarası saniyə': 'Seconds between numbers',
        'Cavab üçün saniyə': 'Seconds for answer',
        'Oyunu başlat': 'Start the game',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Copy the link to start the game',
        'Link Kopyala': 'Copy Link',
    },
    'ru': {
        'Rəqəm sayı': 'Количество цифр',
        'Ədəd sayı': 'Количество чисел',
        'Cavab müddəti': 'Время ответа',
        'İRƏLİ': 'ВПЕРЕД',
        'GERİ': 'НАЗАД',
        'BAŞLA': 'СТАРТ',
        'Formullar': 'Формулы',
        'Formul izahı üçün': 'Для объяснения формулы',
        'ƏL İLƏ İZAH': 'Объяснение вручную',
        'ABAK İLƏ İZAH': 'Объяснение с помощью абака',
        'Rəqəm sayı seç': 'Выберите количество цифр',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Сколько чисел вы хотите использовать в игре?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Выберите количество чисел, с которыми хотите играть',
        'Oyun sayı': 'Количество игр',
        'Oyun sayını qeyd edin': 'Введите количество игр',
        'Rəqəm sayı qarışıq olsun': 'Перемешать количество цифр',
        'Link kopyalandı': 'Ссылка скопирована',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Выберите время появления числа и ответа.',
        'Ədədlərarası saniyə': 'Секунды между числами',
        'Cavab üçün saniyə': 'Секунды для ответа',
        'Oyunu başlat': 'Начать игру',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Скопируйте ссылку, чтобы начать игру',
        'Link Kopyala': 'Скопировать ссылку',
    },
    'tr': {
        'Rəqəm sayı': 'Rakam sayısı',
        'Ədəd sayı': 'Sayı adedi',
        'Cavab müddəti': 'Cevap süresi',
        'İRƏLİ': 'İLERİ',
        'GERİ': 'GERİ',
        'BAŞLA': 'BAŞLA',
        'Formullar': 'Formüller',
        'Formul izahı üçün': 'Formül açıklaması için',
        'ƏL İLƏ İZAH': 'Elle açıklama',
        'ABAK İLƏ İZAH': 'Abaküs ile açıklama',
        'Rəqəm sayı seç': 'Rakam sayısını seç',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Kaç adet sayı ile oynamak istersiniz?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Oynamak istediğiniz sayı adedini seçin',
        'Oyun sayı': 'Oyun sayısı',
        'Oyun sayını qeyd edin': 'Oyun sayısını girin',
        'Rəqəm sayı qarışıq olsun': 'Rakam sayısı karışık olsun',
        'Link kopyalandı': 'Bağlantı kopyalandı',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Sayı ve cevap gelme süresini seçin.',
        'Ədədlərarası saniyə': 'Sayılar arası saniye',
        'Cavab üçün saniyə': 'Cevap için saniye',
        'Oyunu başlat': 'Oyunu başlat',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Oyunu başlatmak için bağlantıyı kopyalayın',
        'Link Kopyala': 'Bağlantıyı Kopyala',
    },
    'pl': {
        'Rəqəm sayı': 'Liczba cyfr',
        'Ədəd sayı': 'Liczba liczb',
        'Cavab müddəti': 'Czas odpowiedzi',
        'İRƏLİ': 'NAPRZÓD',
        'GERİ': 'WSTECZ',
        'BAŞLA': 'START',
        'Formullar': 'Formuły',
        'Formul izahı üçün': 'Do wyjaśnienia formuły',
        'ƏL İLƏ İZAH': 'Wyjaśnienie ręczne',
        'ABAK İLƏ İZAH': 'Wyjaśnienie za pomocą liczydła',
        'Rəqəm sayı seç': 'Wybierz liczbę cyfr',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Ile liczb chcesz użyć w grze?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Wybierz liczbę liczb, z którymi chcesz grać',
        'Oyun sayı': 'Liczba gier',
        'Oyun sayını qeyd edin': 'Wpisz liczbę gier',
        'Rəqəm sayı qarışıq olsun': 'Wymieszaj liczbę cyfr',
        'Link kopyalandı': 'Link skopiowany',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Wybierz czas pojawienia się liczby i odpowiedzi.',
        'Ədədlərarası saniyə': 'Sekundy między liczbami',
        'Cavab üçün saniyə': 'Sekundy na odpowiedź',
        'Oyunu başlat': 'Rozpocznij grę',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Skopiuj link, aby rozpocząć grę',
        'Link Kopyala': 'Kopiuj link',
    },
    'kz': {
        'Rəqəm sayı': 'Сандар саны',
        'Ədəd sayı': 'Сандар саны',
        'Cavab müddəti': 'Жауап уақыты',
        'İRƏLİ': 'АЛҒА',
        'GERİ': 'АРТҚА',
        'BAŞLA': 'БАСТАУ',
        'Formullar': 'Формулалар',
        'Formul izahı üçün': 'Формуланы түсіндіру үшін',
        'ƏL İLƏ İZAH': 'Қолмен түсіндіру',
        'ABAK İLƏ İZAH': 'Абакпен түсіндіру',
        'Rəqəm sayı seç': 'Сандар санын таңдаңыз',
        'Neçə sayda ədəd ilə oyun oynamaq istəyirsiniz?': 'Ойынға қанша санмен ойнағыңыз келеді?',
        'Oynamaq istədiyiniz ədəd sayını seçin': 'Ойнағыңыз келетін сандар санын таңдаңыз',
        'Oyun sayı': 'Ойын саны',
        'Oyun sayını qeyd edin': 'Ойын санын енгізіңіз',
        'Rəqəm sayı qarışıq olsun': 'Сандар саны аралас болсын',
        'Link kopyalandı': 'Сілтеме көшірілді',
        'ƏDƏD və CAVAB gəlmə müddətini seçin.': 'Сандар мен жауап келу уақытын таңдаңыз.',
        'Ədədlərarası saniyə': 'Сандар арасындағы секундтар',
        'Cavab üçün saniyə': 'Жауап үшін секундтар',
        'Oyunu başlat': 'Ойынды бастау',
        'Oyunu başlatmaq üçün linki kopyalayın': 'Ойынды бастау үшін сілтемені көшіріңіз',
        'Link Kopyala': 'Сілтемені көшіру',
    },
}


export default getTranslationWithContent(content);

