import { LangContent, getTranslationWithContent } from "../../HOC/Translation.tsx/Translation";
import { content as formulaLangContent } from "../formules/Lang";


export const content: LangContent = {
    'az': {
        'YENIDƏN OYNA': 'YENIDƏN OYNA',
        'Asan': 'Asan',
        'Normal': 'Normal',
        'Çətin': 'Çətin',
        'BAŞLA': 'BAŞLA',
        'BİTİR': 'BİTİR',
        'GERİ': 'GERİ',
        'IRƏLİ': 'IRƏLİ',
        'YEKUN NƏTİCƏ': 'YEKUN NƏTİCƏ',
        'TEST CAVABI': 'TEST CAVABI',
        'Ümumi nəticəsi': 'Ümumi nəticəsi',
        'Bal-1': 'Bal-1',
        'Bal-1.5': 'Bal-1.5',
        'Bal-2': 'Bal-2',
        'Sən dahisən!': 'Sən dahisən!',
        'Misal sayı': 'Misal sayı',
        'Doğru': 'Doğru',
        'Yanlış': 'Yanlış',
        'Boş': 'Boş',
        'Bal': 'Bal',
        'R': 'R',
        'Ə': 'Ə',
        'Rəqəm Sayı': 'Rəqəm Sayı',
        'Ədəd Sayı': 'Ədəd Sayı',
        'Formul': 'Formul',
        ...formulaLangContent['az'],
    },
    'en': {
        'YENIDƏN OYNA': 'PLAY AGAIN',
        'Asan': 'Easy',
        'Normal': 'Normal',
        'Çətin': 'Hard',
        'BAŞLA': 'START',
        'BİTİR': 'FINISH',
        'GERİ': 'BACK',
        'IRƏLİ': 'NEXT',
        'YEKUN NƏTİCƏ': 'FINAL RESULT',
        'TEST CAVABI': 'TEST ANSWER',
        'Ümumi nəticəsi': 'Total result',
        'Bal-1': 'Score-1',
        'Bal-1.5': 'Score-1.5',
        'Bal-2': 'Score-2',
        'Sən dahisən!': 'You are a genius!',
        'Misal sayı': 'Problem count',
        'Doğru': 'Correct',
        'Yanlış': 'Wrong',
        'Boş': 'Empty',
        'Bal': 'Score',
        'R': 'D',
        'Ə': 'N',
        'Rəqəm Sayı': 'Digit Count',
        'Ədəd Sayı': 'Number Count',
        'Formul': 'Formula',
        ...formulaLangContent['en'],
    },
    'ru': {
        'YENIDƏN OYNA': 'ИГРАТЬ СНОВА',
        'Asan': 'Легко',
        'Normal': 'Нормально',
        'Çətin': 'Сложно',
        'BAŞLA': 'НАЧАТЬ',
        'BİTİR': 'ЗАВЕРШИТЬ',
        'GERİ': 'НАЗАД',
        'IRƏLİ': 'ДАЛЕЕ',
        'YEKUN NƏTİCƏ': 'ИТОГОВЫЙ РЕЗУЛЬТАТ',
        'TEST CAVABI': 'ОТВЕТ ТЕСТА',
        'Ümumi nəticəsi': 'Общий результат',
        'Bal-1': 'Балл-1',
        'Bal-1.5': 'Балл-1.5',
        'Bal-2': 'Балл-2',
        'Sən dahisən!': 'Ты гений!',
        'Misal sayı': 'Номер примера',
        'Doğru': 'Правильно',
        'Yanlış': 'Неправильно',
        'Boş': 'Пусто',
        'Bal': 'Балл',
        'R': 'Ц',
        'Ə': 'Ч',
        'Rəqəm Sayı': 'Количество цифр',
        'Ədəd Sayı': 'Количество чисел',
        'Formul': 'Формула',
        ...formulaLangContent['ru'],
    },
    'tr': {
        'YENIDƏN OYNA': 'TEKRAR OYNA',
        'Asan': 'Kolay',
        'Normal': 'Normal',
        'Çətin': 'Zor',
        'BAŞLA': 'BAŞLA',
        'BİTİR': 'BİTİR',
        'GERİ': 'GERİ',
        'IRƏLİ': 'İLERİ',
        'YEKUN NƏTİCƏ': 'SONUÇ',
        'TEST CAVABI': 'TEST CEVABI',
        'Ümumi nəticəsi': 'Toplam sonuç',
        'Bal-1': 'Puan-1',
        'Bal-1.5': 'Puan-1.5',
        'Bal-2': 'Puan-2',
        'Sən dahisən!': 'Sen bir dahisin!',
        'Misal sayı': 'Örnek sayısı',
        'Doğru': 'Doğru',
        'Yanlış': 'Yanlış',
        'Boş': 'Boş',
        'Bal': 'Puan',
        'R': 'R',
        'Ə': 'S',
        'Rəqəm Sayı': 'Rakam Sayısı',
        'Ədəd Sayı': 'Sayı Adedi',
        'Formul': 'Formül',
        ...formulaLangContent['tr'],
    },
    'pl': {
        'YENIDƏN OYNA': 'GRAJ PONOWNIE',
        'Asan': 'Łatwy',
        'Normal': 'Normalny',
        'Çətin': 'Trudny',
        'BAŞLA': 'START',
        'BİTİR': 'ZAKOŃCZ',
        'GERİ': 'WSTECZ',
        'IRƏLİ': 'DALEJ',
        'YEKUN NƏTİCƏ': 'WYNIK KOŃCOWY',
        'TEST CAVABI': 'ODPOWIEDŹ TESTU',
        'Ümumi nəticəsi': 'Wynik końcowy',
        'Bal-1': 'Punkt-1',
        'Bal-1.5': 'Punkt-1.5',
        'Bal-2': 'Punkt-2',
        'Sən dahisən!': 'Jesteś geniuszem!',
        'Misal sayı': 'Numer przykładu',
        'Doğru': 'Poprawnie',
        'Yanlış': 'Niepoprawnie',
        'Boş': 'Puste',
        'Bal': 'Punkt',
        'R': 'C',
        'Ə': 'L',
        'Rəqəm Sayı': 'Liczba cyfr',
        'Ədəd Sayı': 'Liczba liczb',
        'Formul': 'Formuła',
        ...formulaLangContent['pl'],
    },
    'kz': {
        'YENIDƏN OYNA': 'ҚАЙТА ОЙНАУ',
        'Asan': 'Оңай',
        'Normal': 'Қалыпты',
        'Çətin': 'Қиын',
        'BAŞLA': 'БАСТАУ',
        'BİTİR': 'АЯҚТАУ',
        'GERİ': 'АРТҚА',
        'IRƏLİ': 'АЛҒА',
        'YEKUN NƏTİCƏ': 'ТҰЖЫРЫМДАМА',
        'TEST CAVABI': 'ТЕСТ ЖАУАБЫ',
        'Ümumi nəticəsi': 'Жалпы нәтиже',
        'Bal-1': 'Бал-1',
        'Bal-1.5': 'Бал-1.5',
        'Bal-2': 'Бал-2',
        'Sən dahisən!': 'Сен данышпансың!',
        'Misal sayı': 'Мысал нөмірі',
        'Doğru': 'Дұрыс',
        'Yanlış': 'Қате',
        'Boş': 'Бос',
        'Bal': 'Бал',
        'R': 'Р',
        'Ə': 'С',
        'Rəqəm Sayı': 'Сандар саны',
        'Ədəd Sayı': 'Сандар мөлшері',
        'Formul': 'Формула',
        ...formulaLangContent['kz'],
    },
}


export default getTranslationWithContent(content);

