import { getTranslationWithContent, LangContent } from "../../HOC/Translation.tsx/Translation";


export const content: LangContent = {
    'az': {
        'SƏRBƏST ÇALIŞMA': 'SƏRBƏST ÇALIŞMA',
        'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR': 'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR',
        'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA': 'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA',
        'İKİLİ HESAB': 'İKİLİ HESAB',
        'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR': 'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR',
        'ORDAN-BURDAN ƏDƏDLƏR': 'ORDAN-BURDAN ƏDƏDLƏR',
        'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR': 'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR',
        'MÖTƏRİZƏLİ MİSALLAR': 'MÖTƏRİZƏLİ MİSALLAR',
        'MƏCHULUN TAPILMASI': 'MƏCHULUN TAPILMASI',
        'FAİZ OLAN MİSALLAR': 'FAİZ OLAN MİSALLAR',
        'PUL VAHİDİ': 'PUL VAHİDİ',
        'ÇOXLU PUL VAHİDİ': 'ÇOXLU PUL VAHİDİ',
        'ZAMAN VAHİDLƏRİ': 'ZAMAN VAHİDLƏRİ',
        'UZUNLUQ VAHİDİ': 'UZUNLUQ VAHİDİ',
        'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA': 'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA',
        'SADƏ VURMA': 'SADƏ VURMA',
        'SADƏ BÖLMƏ': 'SADƏ BÖLMƏ',
        'KVADRATA YÜKSƏLTMƏ': 'KVADRATA YÜKSƏLTMƏ',
        'QALIQLI BÖLMƏ': 'QALIQLI BÖLMƏ',
        'KVADRAT KÖK MİSALLARI': 'KVADRAT KÖK MİSALLARI',
        'MUSİQİ SƏSLƏRİ İLƏ HESABLA': 'MUSİQİ SƏSLƏRİ İLƏ HESABLA',
        'HEYVAN SƏSLƏRİ ÜZRƏ': 'HEYVAN SƏSLƏRİ ÜZRƏ',
        'Sənə uyğun əməli seç!': 'Sənə uyğun əməli seç!',
        'kq': 'kq',
        'q': 'q',
        'm': 'm',
        'sm': 'sm',
        'saat': 'saat',
        'dəq': 'dəq',
        'manat': '₼',
        'qəpik': 'qəp',
        'tam': 'tam',
        'qalıq': 'qalıq',
    },
    'en': {
        'SƏRBƏST ÇALIŞMA': 'FREE PRACTICE',
        'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR': 'FREE PRACTICE WITH INVERTED NUMBERS',
        'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA': 'CALCULATE WITH ADDITION, SUBTRACTION AND MULTIPLICATION',
        'İKİLİ HESAB': 'DOUBLE CALCULATION',
        'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR': 'DOUBLE CALCULATION WITH INVERTED NUMBERS',
        'ORDAN-BURDAN ƏDƏDLƏR': 'RANDOM NUMBERS',
        'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR': 'ROTATING RANDOM NUMBERS',
        'MÖTƏRİZƏLİ MİSALLAR': 'EXAMPLES WITH PARENTHESES',
        'MƏCHULUN TAPILMASI': 'FINDING THE UNKNOWN',
        'FAİZ OLAN MİSALLAR': 'PERCENTAGE EXAMPLES',
        'PUL VAHİDİ': 'CURRENCY UNIT',
        'ÇOXLU PUL VAHİDİ': 'MULTIPLE CURRENCY UNITS',
        'ZAMAN VAHİDLƏRİ': 'TIME UNITS',
        'UZUNLUQ VAHİDİ': 'LENGTH UNIT',
        'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA': 'CALCULATE WITH MASS UNITS',
        'SADƏ VURMA': 'SIMPLE MULTIPLICATION',
        'SADƏ BÖLMƏ': 'SIMPLE DIVISION',
        'KVADRATA YÜKSƏLTMƏ': 'SQUARING',
        'QALIQLI BÖLMƏ': 'DIVISION WITH REMAINDER',
        'KVADRAT KÖK MİSALLARI': 'SQUARE ROOT EXAMPLES',
        'MUSİQİ SƏSLƏRİ İLƏ HESABLA': 'CALCULATE WITH MUSICAL SOUNDS',
        'HEYVAN SƏSLƏRİ ÜZRƏ': 'WITH ANIMAL SOUNDS',
        'Sənə uyğun əməli seç!': 'Choose the action that suits you!',
        'kq': 'kg',
        'q': 'g',
        'm': 'm',
        'sm': 'cm',
        'saat': 'h',
        'dəq': 'min',
        'manat': '$',
        'qəpik': '¢',
        'tam': 'whole',
        'qalıq': 'remainder',
    },
    'ru': {
        'SƏRBƏST ÇALIŞMA': 'СВОБОДНАЯ ПРАКТИКА',
        'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR': 'СВОБОДНАЯ ПРАКТИКА С ПЕРЕВЕРНУТЫМИ ЧИСЛАМИ',
        'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA': 'ВЫЧИСЛЕНИЯ СО СЛОЖЕНИЕМ, ВЫЧИТАНИЕМ И УМНОЖЕНИЕМ',
        'İKİLİ HESAB': 'ДВОЙНОЙ РАСЧЕТ',
        'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR': 'ДВОЙНОЙ РАСЧЕТ С ПЕРЕВЕРНУТЫМИ ЧИСЛАМИ',
        'ORDAN-BURDAN ƏDƏDLƏR': 'СЛУЧАЙНЫЕ ЧИСЛА',
        'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR': 'ВРАЩАЮЩИЕСЯ СЛУЧАЙНЫЕ ЧИСЛА',
        'MÖTƏRİZƏLİ MİSALLAR': 'ПРИМЕРЫ СО СКОБКАМИ',
        'MƏCHULUN TAPILMASI': 'ПОИСК НЕИЗВЕСТНОГО',
        'FAİZ OLAN MİSALLAR': 'ПРИМЕРЫ С ПРОЦЕНТАМИ',
        'PUL VAHİDİ': 'ДЕНЕЖНАЯ ЕДИНИЦА',
        'ÇOXLU PUL VAHİDİ': 'МНОЖЕСТВЕННЫЕ ДЕНЕЖНЫЕ ЕДИНИЦЫ',
        'ZAMAN VAHİDLƏRİ': 'ЕДИНИЦЫ ВРЕМЕНИ',
        'UZUNLUQ VAHİDİ': 'ЕДИНИЦА ДЛИНЫ',
        'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA': 'РАСЧЕТ С ЕДИНИЦАМИ МАССЫ',
        'SADƏ VURMA': 'ПРОСТОЕ УМНОЖЕНИЕ',
        'SADƏ BÖLMƏ': 'ПРОСТОЕ ДЕЛЕНИЕ',
        'KVADRATA YÜKSƏLTMƏ': 'ВОЗВЕДЕНИЕ В КВАДРАТ',
        'QALIQLI BÖLMƏ': 'ДЕЛЕНИЕ С ОСТАТКОМ',
        'KVADRAT KÖK MİSALLARI': 'ПРИМЕРЫ С КВАДРАТНЫМ КОРНЕМ',
        'MUSİQİ SƏSLƏRİ İLƏ HESABLA': 'ВЫЧИСЛЕНИЯ СО ЗВУКАМИ МУЗЫКИ',
        'HEYVAN SƏSLƏRİ ÜZRƏ': 'СО ЗВУКАМИ ЖИВОТНЫХ',
        'Sənə uyğun əməli seç!': 'Выберите подходящее действие!',
        'kq': 'кг',
        'q': 'г',
        'm': 'м',
        'sm': 'см',
        'saat': 'ч',
        'dəq': 'мин',
        'manat': '₽',
        'qəpik': 'к',
        'tam': 'целое',
        'qalıq': 'остаток',
    },
    'tr': {
        'SƏRBƏST ÇALIŞMA': 'SERBEST ÇALIŞMA',
        'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR': 'TERS SAYILARLA SERBEST ÇALIŞMA',
        'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA': 'TOPLAMA, ÇIKARMA VE ÇARPMA İŞLEMLERİYLE HESAPLAMA',
        'İKİLİ HESAB': 'İKİLİ HESAPLAMA',
        'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR': 'TERS SAYILARLA İKİLİ HESAPLAMA',
        'ORDAN-BURDAN ƏDƏDLƏR': 'RASTGELE SAYILAR',
        'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR': 'DÖNEN RASTGELE SAYILAR',
        'MÖTƏRİZƏLİ MİSALLAR': 'PARANTEZLİ ÖRNEKLER',
        'MƏCHULUN TAPILMASI': 'BİLİNMEYENİ BULMA',
        'FAİZ OLAN MİSALLAR': 'YÜZDELİ ÖRNEKLER',
        'PUL VAHİDİ': 'PARA BİRİMİ',
        'ÇOXLU PUL VAHİDİ': 'ÇOKLU PARA BİRİMLERİ',
        'ZAMAN VAHİDLƏRİ': 'ZAMAN BİRİMLERİ',
        'UZUNLUQ VAHİDİ': 'UZUNLUK BİRİMİ',
        'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA': 'KÜTLE BİRİMLERİYLE HESAPLAMA',
        'SADƏ VURMA': 'BASİT ÇARPMA',
        'SADƏ BÖLMƏ': 'BASİT BÖLME',
        'KVADRATA YÜKSƏLTMƏ': 'KAREYE YÜKSELTME',
        'QALIQLI BÖLMƏ': 'KALANI BÖLME',
        'KVADRAT KÖK MİSALLARI': 'KAREKÖK ÖRNEKLERİ',
        'MUSİQİ SƏSLƏRİ İLƏ HESABLA': 'MÜZİK SESLERİYLE HESAPLAMA',
        'HEYVAN SƏSLƏRİ ÜZRƏ': 'HAYVAN SESLERİYLE',
        'Sənə uyğun əməli seç!': 'Sana uygun işlemi seç!',
        'kq': 'kg',
        'q': 'g',
        'm': 'm',
        'sm': 'cm',
        'saat': 'saat',
        'dəq': 'dk',
        'manat': '₺',
        'qəpik': 'kr',
        'tam': 'tam',
        'qalıq': 'kalan',
    },
    'pl': {
        'SƏRBƏST ÇALIŞMA': 'SWOBODNA PRAKTYKA',
        'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR': 'SWOBODNA PRAKTYKA Z ODWRÓCONYMI LICZBAMI',
        'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA': 'OBLICZENIA Z DODAWANIEM, ODEJMOWANIEM I MNOŻENIEM',
        'İKİLİ HESAB': 'PODWÓJNE OBLICZENIE',
        'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR': 'PODWÓJNE OBLICZENIE Z ODWRÓCONYMI LICZBAMI',
        'ORDAN-BURDAN ƏDƏDLƏR': 'LOSOWE LICZBY',
        'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR': 'OBRACAJĄCE SIĘ LOSOWE LICZBY',
        'MÖTƏRİZƏLİ MİSALLAR': 'PRZYKŁADY Z NAWIASAMI',
        'MƏCHULUN TAPILMASI': 'ZNAJDOWANIE NIEWIADOMEJ',
        'FAİZ OLAN MİSALLAR': 'PRZYKŁADY Z PROCENTAMI',
        'PUL VAHİDİ': 'JEDNOSTKA WALUTOWA',
        'ÇOXLU PUL VAHİDİ': 'WIELOKROTNE JEDNOSTKI WALUTOWE',
        'ZAMAN VAHİDLƏRİ': 'JEDNOSTKI CZASU',
        'UZUNLUQ VAHİDİ': 'JEDNOSTKA DŁUGOŚCI',
        'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA': 'OBLICZENIA Z JEDNOSTKAMI MASY',
        'SADƏ VURMA': 'PROSTE MNOŻENIE',
        'SADƏ BÖLMƏ': 'PROSTE DZIELENIE',
        'KVADRATA YÜKSƏLTMƏ': 'PODNOSZENIE DO KWADRATU',
        'QALIQLI BÖLMƏ': 'DZIELENIE Z RESZTĄ',
        'KVADRAT KÖK MİSALLARI': 'PRZYKŁADY Z PIERWIASTKIEM KWADRATOWYM',
        'MUSİQİ SƏSLƏRİ İLƏ HESABLA': 'OBLICZENIA Z DŹWIĘKAMI MUZYCZNYMI',
        'HEYVAN SƏSLƏRİ ÜZRƏ': 'Z DŹWIĘKAMI ZWIERZĄT',
        'Sənə uyğun əməli seç!': 'Wybierz odpowiednie dla siebie działanie!',
        'kq': 'kg',
        'q': 'g',
        'm': 'm',
        'sm': 'cm',
        'saat': 'godz',
        'dəq': 'min',
        'manat': 'zł',
        'qəpik': 'gr',
        'tam': 'całość',
        'qalıq': 'reszta',
    },
    'kk': {
        'SƏRBƏST ÇALIŞMA': 'ЕРКІН ПРАКТИКА',
        'SƏRBƏST ÇALIŞMA TƏRSINE ƏDƏDLƏR': 'ТӨҢКЕРІЛГЕН САНДАРМЕН ЕРКІН ПРАКТИКА',
        'TOPLAMA, ÇIXMA VƏ VURMA ƏMƏLLƏRİ BİRGƏ HESABLA': 'ҚОСУ, АЛЫП ТАСТАУ ЖӘНЕ КӨБЕЙТУ АМАЛДАРЫМЕН ЕСЕПТЕУ',
        'İKİLİ HESAB': 'ҚОСАРЛЫ ЕСЕПТЕУ',
        'İKİLİ HESAB üzrə TƏRSINE ƏDƏDLƏR': 'ТӨҢКЕРІЛГЕН САНДАРМЕН ҚОСАРЛЫ ЕСЕПТЕУ',
        'ORDAN-BURDAN ƏDƏDLƏR': 'КЕЗДЕЙСОҚ САНДАР',
        'ORDAN-BURDAN DÖNƏN ƏDƏDLƏR': 'АЙНАЛМАЛЫ КЕЗДЕЙСОҚ САНДАР',
        'MÖTƏRİZƏLİ MİSALLAR': 'ЖАҚШАЛЫ МЫСАЛДАР',
        'MƏCHULUN TAPILMASI': 'БЕЛГІСІЗДІ ТАБУ',
        'FAİZ OLAN MİSALLAR': 'ПАЙЫЗДЫҚ МЫСАЛДАР',
        'PUL VAHİDİ': 'АҚША БІРЛІГІ',
        'ÇOXLU PUL VAHİDİ': 'КӨПТІК АҚША БІРЛІКТЕРІ',
        'ZAMAN VAHİDLƏRİ': 'УАҚЫТ БІРЛІКТЕРІ',
        'UZUNLUQ VAHİDİ': 'ҰЗЫНДЫҚ БІРЛІГІ',
        'KÜTLƏ VAHİDLƏRİ ÜZRƏ HESABLA': 'МАССА БІРЛІКТЕРІМЕН ЕСЕПТЕУ',
        'SADƏ VURMA': 'ҚАРАПАЙЫМ КӨБЕЙТУ',
        'SADƏ BÖLMƏ': 'ҚАРАПАЙЫМ БӨЛУ',
        'KVADRATA YÜKSƏLTMƏ': 'КВАДРАТҚА КӨТЕРУ',
        'QALIQLI BÖLMƏ': 'ҚАЛДЫҚПЕН БӨЛУ',
        'KVADRAT KÖK MİSALLARI': 'КВАДРАТ ТҮБІР МЫСАЛДАРЫ',
        'MUSİQİ SƏSLƏRİ İLƏ HESABLA': 'МУЗЫКА ДЫБЫСТАРЫМЕН ЕСЕПТЕУ',
        'HEYVAN SƏSLƏRİ ÜZRƏ': 'ЖАНУАРЛАР ДЫБЫСТАРЫМЕН',
        'Sənə uyğun əməli seç!': 'Сізге сәйкес әрекетті таңдаңыз!',
        'kq': 'кг',
        'q': 'г',
        'm': 'м',
        'sm': 'см',
        'saat': 'сағ',
        'dəq': 'мин',
        'manat': '₸',
        'qəpik': 'тиын',
        'tam': 'бүтін',
        'qalıq': 'қалдық',
    }
}

export default getTranslationWithContent(content);
